# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! 
  Admin will get back to you soon.
  Meanwhile check [this](https://github.com/prathimacode-hub/HelloWorld/) repo for more.
  
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! ğŸ¤—
 **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/prathimacode-hub/HelloWorld/) repo.**
  
 [![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/prathimacode-hub/)
 
 Show some love by starring a few of my [projects](https://github.com/prathimacode-hub/prathimacode-hub/blob/main/PROJECTS.md).ğŸš€

 PS: Please add @prathimacode-hub as a reviewer if you haven't added.
 
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
 Show some love by starring a few of my [projects](https://github.com/prathimacode-hub/prathimacode-hub/blob/main/PROJECTS.md).
