# first time issues

newIssueWelcomeComment: |
  Thanks for opening your first issue! 

# PRs from first time contributors in your repository

newPRWelcomeComment: |
 Thanks for opening this pull request! ğŸ¤—
 
# pull requests merged by a first time user

firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
